org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.caching.debug=false
#org.gradle.configureondemand=true

mod.id=pullup
mod.name=PullUp+
mod.version=2.1.1
mod.group=cool.muyucloud.pullup
mod.description=A maintained multi-version fork of PullUp that adds customizable pull-up warnings to Minecraft flight.
