modLoader = "javafml"
loaderVersion = "*"
license = "GPL-3.0-only"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "cc_cece"
description = '''
${description}
'''
logoFile = "icon.png"
logoBlur = false

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraftDependencyRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "pullup.mixins.json"
